version: '3'

services:
  #Elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    network_mode: host
    environment:
      - discovery.type=single-node

  # Kafka:9092
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    network_mode: host
    depends_on:
      - zookeeper

  # Zookeeper:2181
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"

  # API
#  api:
#    build:
#      context: .
#    image: chatbot-image
#    network_mode: host
#    command: [
#      "java",
#      "-jar",
#      "-Dspring.config.name=application",
#      "-Dspring.config.location=file:application.properties",
#      "app.jar"
#    ]
