version: '3'

services:
  #Elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"


#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "my-topic:1:1"

  redis:
    image: redis:6.2-alpine
    ports:
      - 6380:6379
    volumes:
      - /Users/caodinhsyvy/DATA/CapstoneProject/redisData:/data

# API
  api:
    build:
      context: .
    image: chatbot-image
    network_mode: host
    ports:
      - 8085:8085
    command: [
      "java",
      "-jar",
      "-Dspring.config.name=application",
      "-Dspring.config.location=file:application.properties",
      "app.jar"
    ]

